#!/usr/bin/env python
# -*- coding: utf8 -*-

ERROR_WRONG_ARGUMENTS = 1
ERROR_GIT_CHANGES_PENDING = 2
ERROR_UNKNOWN_OPTION = 3
ERROR_REQUIRED_MODULE_MISSING = 4
ERROR_NOT_AT_ROOT = 5
ERROR_FILE_NOT_FOUND = 6
